steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'functions', 'deploy', 'SyncItems',
      '--runtime', 'go111',
      '--trigger-topic', 'syncItems',
      '--source', '.',
      '--memory', '128MB',
      '--region', 'us-central1',
      '--timeout', '60s'
    ]
